services:
  #-----------------------------------
  #---- Bridgewell GPT services ---------
  #-----------------------------------
  bridgewell-gpt-openai:
    image: ${PGPT_IMAGE:-bridgewell-gpt}:${PGPT_TAG:-0.6.2}-openai
    user: root
    build:
      context: .
      dockerfile: Dockerfile.openai
    volumes:
      - ./local_data:/home/worker/app/local_data
      - ./bridgewell_gpt:/home/worker/app/bridgewell_gpt
      - ./settings.yaml:/home/worker/app/settings.yaml
      - ./settings-openai.yaml:/home/worker/app/settings-openai.yaml
      - ./.env:/home/worker/app/.env
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      PGPT_PROFILES: openai
      PGPT_MODE: openai
      PGPT_OPENAI_API_KEY: ${OPENAI_API_KEY}
      PGPT_EMBED_MODE: openai
      PGPT_OPENAI_MODEL: gpt-4o
      PGPT_DEV_MODE: "true" # Enable development mode with auto-reload
      LLAMA_CLOUD_API_KEY: ${LLAMA_CLOUD_API_KEY}
    profiles:
      - openai
