export const BENEFIT_FIELDS = {
  life_insurance_ad_d: [
    "schedule",
    "reduction",
    "non_evidence_maximum",
    "termination_age",
  ],
  dependent_life: ["schedule", "termination_age"],
  critical_illness: ["schedule", "impairments", "termination_age"],
  long_term_disability: [
    "schedule",
    "maximum_monthly_benefit",
    "tax_status",
    "elimination_period",
    "benefit_period",
    "definition",
    "offsets",
    "cost_of_living_adjustment",
    "pre_existing",
    "survivor_benefit",
    "non_evidence_maximum",
    "termination_age",
  ],
  short_term_disability: [
    "schedule",
    "elimination_period",
    "maximum_benefit_period",
    "maximum_monthly_benefit",
    "non_evidence_maximum",
    "termination_age",
  ],
  health_care: [
    "prescription_drugs",
    "pay_direct_drug_card",
    "maximum",
    "fertility_drugs",
    "smoking_cessations",
    "vaccines",
    "major_medical",
    "annual_deductible",
    "hospitalization",
    "orthotic_shoes",
    "orthotic_inserts",
    "hearing_aids",
    "vision_care",
    "eye_exams",
    "paramedical_practitioners",
    "included_specialists",
    "out_of_country",
    "maximum_duration",
    "trip_cancellation",
    "private_duty_nursing",
    "survivor_benefit",
    "termination_age",
  ],
  dental_care: [
    "annual_deductible",
    "basic_preventative",
    "periodontic_endodontic",
    "annual_maximum",
    "major_restorative_services",
    "orthodontic_services",
    "lifetime_maximum",
    "recall_frequency",
    "scaling_rooting_units",
    "white_filings",
    "fee_guide",
    "survivor_benefit",
    "termination_age",
  ],
  notes_and_definitions: ["notes", "definitions"],
} as const;
